name: voting-app

services:
  vote-stack:
    public: true
    build: vote
    replicas: 2
    ports:
      - 8080

  redis-stack:
    image: redis
    ports:
      - 6379
    volumes:
      - redis-stack:/data

volumes:
  redis-stack:
    size: 1Gi
