on:
  pull_request:
    branches:
      - master

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: Login
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: "Activate namespace"
      uses: okteto/namespace@master
      with:
        namespace: ci-ifbyol

    - name: Deploy Stack
      uses: okteto/deploy-stack@ifbyol/update-okteto-cli-1-12-11
      with:
        namespace: ci-ifbyol
        name: test-vote
        build: true
